### ISSUE TITLE
Add JMH test to repository.

### ISSUE THREAD

**Issue by solonovamax** [vigna/dsiutils#4]
In the [package summary for Package it.unimi.dsi.util](https://dsiutils.di.unimi.it/docs/it/unimi/dsi/util/package-summary.html), it says

> The timings were measured on an Intel® Core™ i7-8700B CPU @3.20GHz using [JMH](http://openjdk.java.net/projects/code-tools/jmh/) microbenchmarks

Where are these JMH tests that have been run? How reproducible are they? What java version was it run on?

It seems these tests were first added back in 2016 (according to the `CHANGES` file, they were added in version `2.3.3`, which was released in 2016 on maven central), so are these results outdated?

They should almost certainly be re-run with newer java versions, as there have been many performance improvements since then.

**Comment by vigna** [comment]
That's a very good point. Sorry for the late answer, but an email mess left me without most Github notifications since May 2022. It should be really easy to add the benchmark code, and people could easily try them with different architectures, OSs and Java versions. It's a win-win.

**Comment by solonovamax** [comment]
Alright, sick

**Comment by vigna** [comment]
I added the PRNG performance tests. Feel free to try. I have recently tried GraalVM and the increase in speed is spectacular (xorshift128+ is below 1ns). I will update the timings in the documentation at some point.
